# config/camera_params.yaml
go2:
  d435i:
    ros__parameters:
      align_depth.enable: true
      enable_sync: true
      enable_infra1: false
      enable_infra2: false

      color_profile: "640x480x30"
      depth_profile: "640x480x30"
      color_format: "RGB8"
      depth_format: "Z16"

      initial_reset: false
      unite_imu_method: 2
      publish_tf: false

      color_qos: "SENSOR_DATA"
      depth_qos: "SENSOR_DATA"

